name: Build Firmware

on: [push, pull_request]
jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      run: make -j$(nproc)
